export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const SELECT_SIZE = 'SELECT_SIZE';
export const TOGGLE_INGREDIENT = 'TOGGLE_INGREDIENT';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const SELECT_DELIVERY = 'SELECT_DELIVERY';